AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Berez API - Drinking Fountain Finder Backend (Free Tier)

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
  
  JWTSecretKey:
    Type: String
    NoEcho: true
    MinLength: 32
  
  FrontendURL:
    Type: String
    Default: https://berez.vercel.app

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11

Resources:
  # ==================== API Gateway ====================
  BerezApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins:
          - !Ref FrontendURL
          - "http://localhost:3000"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowCredentials: true

  # ==================== Lambda Function ====================
  BerezFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub berez-api-${Environment}
      CodeUri: .
      Handler: lambda_handler.handler
      Description: Berez FastAPI application
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          JWT_SECRET_KEY: !Ref JWTSecretKey
          APP_URL: !Ref FrontendURL
          S3_BUCKET: !Ref PhotosBucket
          DB_BUCKET: !Ref DataBucket
          AWS_REGION_NAME: !Ref AWS::Region
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PhotosBucket
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BerezApi
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BerezApi
            Path: /
            Method: ANY

  # ==================== S3 Bucket for Photos ====================
  PhotosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub berez-photos-${Environment}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - !Ref FrontendURL
              - "http://localhost:3000"
            MaxAge: 3000

  PhotosBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PhotosBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub ${PhotosBucket.Arn}/*

  # ==================== S3 Bucket for SQLite Database ====================
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub berez-data-${Environment}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${BerezApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
  
  PhotosBucketName:
    Description: S3 bucket for photos
    Value: !Ref PhotosBucket
  
  PhotosBucketURL:
    Description: S3 bucket URL for photos
    Value: !Sub "https://${PhotosBucket}.s3.${AWS::Region}.amazonaws.com"
  
  DataBucketName:
    Description: S3 bucket for database
    Value: !Ref DataBucket
